### PR TITLE
Hannes/reply codes

### PR DESCRIPTION
**Pull request by hannesdejager**
Hi Koen, 

I thought we could do away with some of the repetitiveness of the replies. Here is my suggestion. I'm sure it can be improved more so feel free to add commits or comments. Hope it helps.

### CODE REVIEW

**Comment by hannesdejager** [comment]
@koenw let me know what you think :-)

**Comment by hannesdejager** [comment]
Koen, sorry for being persistent but its important for our project to keep the flow here? Can you look at this? Thanks

**Comment by koenw** [comment]
Hi Hannes, sorry for the late reply, I've been very busy.

This looks like a very nice refactory, thanks!

**Comment by hannesdejager** [comment]
cool, thanks for the merge!

**Pull request merged**
